### ISSUE TITLE
FR: Add Support for arrays and/or delaying Jamf inventory update for bootstrap workflows

### ISSUE THREAD

**Issue by apizz** [dataJAR/jamJAR#10]
Trying to work out a bootstrap software install workflow that would utilize jamJAR, so we avoid having to configure any manifests in munki (outside those which simply define the catalog for the machine via the `ClientIdentifier` in the ManagedInstalls.plist) and similarly which avoid having to create many policies in jamf.

Complicating the workflow at the moment is the fact that software titles can only be added one at a time to the managed_installs or managed_uninstalls in the Local Manifest, and that as part of the jamJAR postflight an inventory update is completed after each install or uninstall.

I have two thoughts in this regard:

1. Add support for arrays so ` jamJAR.py` can be added to a Jamf policy once so multiple pieces of software could be added to the managed installs and/or uninstalls.

OR

2. Add support to forcibly prevent an inventory update via the postflight following a single software install.  This way the `jamJAR.py` script could be added multiple times to a single policy, installing software one at a time, but then only update inventory at the end.
    * In this regard, I know jamf has some logic so that if multiple policies are triggered that have inventory updates configured this only happens once all policies have finished running.

**Comment by macmule** [comment]
What’s the want for 2?

We run a recon after every install & there are no issues.

**Comment by apizz** [comment]
There isn't actually a want for 2.  The thought was that it might be easier to add a "suppress inventory collection" element than adding support for arrays.

Conceivably if we take a machine out of the box and our jamJAR policies get triggered to install the necessary software a machine needs, an inventory update would be collected many times, rather than just once at the end, therefore taking longer.

**Comment by macmule** [comment]
jamJAR.py doesn’t call recon, the postflight does.

The postflight runs a recon whenever a new item is installed, as you mentioned.

So.. the idea would be to have a flag that says “software installed”.. but, the postflight won’t know if we’re at the beginning of a Munki run or end & where we are in the manifest. 

I can’t see a way to implement this.

**Comment by apizz** [comment]
In that case I'll try and create a PR that supports arrays
