### ISSUE TITLE
Add ability to use GitHubReleasesInfoProvider for autopkg recipe

### ISSUE THREAD

**Issue by apizz** [dataJAR/jamJAR#11]
Tried to create an autopkg recipe to download the latest release so I could feed the latest postflight script into munki, but for whatever reason despite jamJAR having a version listed and downloadable assets the `GitHubReleasesInfoProvider` returns the following error:

`Error in com.github.apizz.download.jamJAR: Processor: GitHubReleasesInfoProvider: Error: No release assets were found that satisfy the criteria.`

As a result, my current working recipe pulls the version tag from the ./releases/latest url redirect to complete a direct download.

**Comment by macmule** [comment]
The release just contains the source code.

As there is a few items here, & folks might not use them all there is no need to put them in another format IMO.

Also, if someone is using Sal or Munkireport they will need to rename the postflight too.

**Comment by apizz** [comment]
Fair enough.  I'll keep my recipe as is.
