### ISSUE TITLE
jamJAR & munki manifest double-install niche condition

### ISSUE THREAD

**Issue by apizz** [dataJAR/jamJAR#17]
This is more for me to hopefully address in a future PR, but wanted to get it here.  It's a pretty niche issue, and I'm not 100% sure how to address it.

We're using munki manifests, rather than policies, to ensure all of our machines have the base software they need and then use jamJAR for Self Service and certain automated policies.

We have a scenario where a user who has our org VPN configured and forcibly applied when off LAN (which is the default) is traveling abroad and therefore needs to be able to manually choose when to turn on and off VPN, as some planes and trains restrict VPN traffic or force you to poney up more $$.

To accommodate this, we have two VPN app items, which reference the same PKG installer.  However, one has the forced config item as an `update_for` and the other does not.  

In this scenario, the VPN w/ config item is part of the `included_manifest` chain while the VPN w/o the config is not.  I ran an uninstall from Self Service to remove the existing VPN app and config file and then ran a second Self Service policy to reinstall the VPN app w/o the config.  Because these are two different items, the VPN installer is run twice - once from the default manifest and once from the `LocalOnly` manifest - and then installs the config.

Again, very niche ...

**Comment by macmule** [comment]
So your using manifests + jamjar? (which is meant to only work with a local manifest)

**Comment by apizz** [comment]
correct

**Comment by macmule** [comment]
Erm.. don’t do that.

Your very much crossing the streams here.

Either use vanilla Munki.. or have jamjar manage the local manifest...

Anything else’s behaviour is “undefined”

**Comment by apizz** [comment]
👌
