### ISSUE TITLE
Duplicate notifications from jamJAR

### ISSUE THREAD

**Issue by rquigley-aus** [dataJAR/jamJAR#36]
Hello,

I've noticed an issue with how jamJAR interacts with the Jamf Management Action in showing duplicate notifications for the installation or updating of software as shown below: 

<img width="356" alt="Screen Shot 2022-10-06 at 3 13 10 pm" src="https://user-images.githubusercontent.com/85332340/202368812-78d14274-902d-4f6f-9ecd-20b193371417.png">

This was discussed on the #jamjar channel on the MacAdmins Slack and others mentioned this shows up using Notifier as well. https://macadmins.slack.com/archives/C3P30M36F/p1665029649572419

Just wanted to let you know in hopes it could be addressed.

Many thanks for the project and all you do!

**Comment by macmule** [comment]
Just realised this is related to #34

**Comment by macmule** [comment]
Resolved in 2.1 :)
